import { Product } from './types';

export const products: Product[] = [
  {
    id: 'panasonic-premium-15',
    name: 'Premium Inverter Split Type',
    brand: 'Panasonic',
    category: 'Split Type AC',
    price: 38500,
    originalPrice: 42000,
    rating: 4.9,
    sold: 234,
    image: '/hero-bg.png',
    badge: 'BEST SELLER',
    specs: ['1.5 HP', 'Inverter Technology', 'R-32 Refrigerant', 'AEROWINGS Airflow', '5-Year Compressor Warranty'],
    description: 'Experience superior comfort with Panasonic\'s Premium Inverter featuring AEROWINGS for wider and farther airflow. Energy-efficient R-32 refrigerant and nanoe™ X technology for cleaner air.',
  },
  {
    id: 'carrier-optima-10',
    name: 'Optima Green Window Type',
    brand: 'Carrier',
    category: 'Window Type AC',
    price: 16990,
    originalPrice: 19990,
    rating: 4.7,
    sold: 1200,
    image: '/hero-bg.png',
    badge: 'FREE SHIPPING',
    specs: ['1.0 HP', 'Non-Inverter', 'R-32 Eco Refrigerant', 'Auto Swing', '1-Year Parts Warranty'],
    description: 'The Carrier Optima Green delivers reliable cooling with eco-friendly R-32 refrigerant. Perfect for small to medium rooms with auto-swing louvers for even distribution.',
  },
  {
    id: 'lg-dual-inverter-30',
    name: 'Dual Inverter Floor Standing',
    brand: 'LG',
    category: 'Floor Standing AC',
    price: 85000,
    rating: 4.8,
    sold: 56,
    image: '/hero-bg.png',
    badge: 'PREMIUM',
    specs: ['3.0 HP', 'Dual Inverter Compressor', 'ThinQ Wi-Fi', 'Active Energy Control', '10-Year Compressor Warranty'],
    description: 'LG\'s powerful floor-standing unit with Dual Inverter Compressor™ for maximum energy savings and faster cooling. Smart ThinQ Wi-Fi connectivity for remote control.',
  },
  {
    id: 'daikin-standard-20',
    name: 'Refurbished Standard Split',
    brand: 'Daikin',
    category: 'Pre-Owned AC',
    price: 22000,
    originalPrice: 45000,
    rating: 4.5,
    sold: 89,
    image: '/hero-bg.png',
    badge: '51% OFF',
    specs: ['2.0 HP', 'Factory Reconditioned', 'R-410A Refrigerant', 'Quiet Operation', '6-Month Warranty'],
    description: 'Certified refurbished Daikin unit — professionally restored to factory standards. Incredible value with 6-month comprehensive warranty included.',
  },
  {
    id: 'samsung-wind-free-10',
    name: 'Wind-Free™ Cooling Inverter',
    brand: 'Samsung',
    category: 'Split Type AC',
    price: 32990,
    originalPrice: 36990,
    rating: 4.6,
    sold: 145,
    image: '/hero-bg.png',
    specs: ['1.0 HP', 'Wind-Free™ Technology', 'AI Auto Comfort', 'Fast Cooling', '5-Year Warranty'],
    description: 'Samsung Wind-Free™ technology disperses cool air through 23,000 micro holes for a gentle breeze without the discomfort of direct cold airflow.',
  },
  {
    id: 'midea-xtreme-15',
    name: 'Xtreme Save Inverter',
    brand: 'Midea',
    category: 'Split Type AC',
    price: 25990,
    originalPrice: 29990,
    rating: 4.4,
    sold: 312,
    image: '/hero-bg.png',
    badge: 'VALUE PICK',
    specs: ['1.5 HP', 'Inverter Compressor', 'iECO Mode', 'Follow Me Function', '10-Year Warranty'],
    description: 'Midea\'s best-selling inverter AC with iECO energy-saving mode. Budget-friendly with premium features — perfect for Filipino homes.',
  },
];
