import { Product } from './types';

export const products: Product[] = [
  {
    id: 'carrier-inverter-10',
    name: 'Carrier Inverter',
    brand: 'Carrier',
    category: 'Split Type AC',
    price: 32000,
    originalPrice: 35000,
    rating: 4.8,
    sold: 120,
    image: '/hero-bg.png',
    badge: 'BEST SELLER',
    specs: ['1.0 HP', 'Inverter Technology', 'R-32 Eco Refrigerant', 'Fast Cooling'],
    description: 'Reliable cooling with eco-friendly R-32 refrigerant. Perfect for small to medium rooms with fast cooling technology.',
  },
  {
    id: 'chiq-inverter-10',
    name: 'Chiq Inverter',
    brand: 'Chiq',
    category: 'Split Type AC',
    price: 18500,
    originalPrice: 20000,
    rating: 4.5,
    sold: 80,
    image: '/hero-bg.png',
    badge: 'VALUE PICK',
    specs: ['1.0 HP', 'Inverter Technology', 'Energy Saving', 'Quiet Operation'],
    description: 'Affordable and energy-efficient Chiq Inverter AC. Great value for your cooling needs without breaking the bank.',
  },
  {
    id: 'iffalcon-inverter-10',
    name: 'iFFALCON Inverter',
    brand: 'iFFALCON',
    category: 'Split Type AC',
    price: 19900,
    originalPrice: 22000,
    rating: 4.6,
    sold: 60,
    image: '/hero-bg.png',
    specs: ['1.0 HP', 'Inverter Compressor', 'Smart AI', 'Fast Cooling'],
    description: 'Smart and efficient iFFALCON Inverter AC. Experience modern cooling with advanced AI comfort features.',
  },
  {
    id: 'midea-full-dc-15',
    name: 'Midea Full DC Inverter',
    brand: 'Midea',
    category: 'Split Type AC',
    price: 26500,
    originalPrice: 29000,
    rating: 4.7,
    sold: 150,
    image: '/hero-bg.png',
    badge: 'ENERGY SAVER',
    specs: ['1.5 HP', 'Full DC Inverter', 'iECO Mode', 'Follow Me Function'],
    description: 'Midea\'s advanced Full DC Inverter with iECO energy-saving mode. Maximizes energy efficiency while delivering powerful cooling.',
  },
  {
    id: 'samsung-inverter-15',
    name: 'Samsung Inverter',
    brand: 'Samsung',
    category: 'Split Type AC',
    price: 35000,
    originalPrice: 38000,
    rating: 4.9,
    sold: 210,
    image: '/hero-bg.png',
    badge: 'PREMIUM',
    specs: ['1.5 HP', 'Digital Inverter', 'Fast Cooling', 'Anti-bacterial Filter'],
    description: 'Premium Samsung Inverter AC. Enjoy ultra-fast cooling and cleaner air with advanced digital inverter technology.',
  },
  {
    id: 'tcl-split-inverter-10',
    name: 'TCL Split type Inverter',
    brand: 'TCL',
    category: 'Split Type AC',
    price: 16990,
    originalPrice: 18990,
    rating: 4.4,
    sold: 300,
    image: '/hero-bg.png',
    badge: 'MOST POPULAR',
    specs: ['1.0 HP', 'Inverter', 'TitanGold Technology', 'Low Noise'],
    description: 'Highly popular TCL Split type Inverter. Reliable, affordable, and features TitanGold fins for better durability and air quality.',
  },
  {
    id: 'carrier-inverter-compressor',
    name: 'Inverter Compressor Unit',
    brand: 'Carrier',
    category: 'Spare Parts',
    price: 8500,
    rating: 4.9,
    sold: 15,
    image: '/hero-bg.png',
    badge: 'GENUINE',
    specs: ['Genuine Part', 'Inverter Compressor', 'High Efficiency'],
    description: 'Genuine Carrier Inverter Compressor Unit. Perfect replacement to keep your unit running efficiently.',
  },
  {
    id: 'samsung-air-filter',
    name: 'High-Efficiency Air Filter',
    brand: 'Samsung',
    category: 'Spare Parts',
    price: 1200,
    rating: 4.8,
    sold: 45,
    image: '/service-bg.png',
    specs: ['High-Efficiency', 'Washable', 'Easy Install'],
    description: 'High-Efficiency Air Filter for Samsung ACs. Improves air quality instantly and easy to replace.',
  },
  {
    id: 'tcl-remote-control',
    name: 'Universal Remote Control',
    brand: 'TCL',
    category: 'Spare Parts',
    price: 850,
    rating: 4.5,
    sold: 80,
    image: '/hero-bg.png',
    specs: ['Universal', 'Batteries Included', 'LCD Display'],
    description: 'Replacement remote control for TCL AC units. Full functionality including timer and swing controls.',
  },
  {
    id: 'midea-capacitor',
    name: 'Dual Run Capacitor 45+5 uF',
    brand: 'Midea',
    category: 'Spare Parts',
    price: 600,
    rating: 4.6,
    sold: 30,
    image: '/service-bg.png',
    specs: ['45+5 uF', 'Dual Run', 'High Durability'],
    description: 'High-quality dual run capacitor for Midea AC units. Gets your compressor and fan running efficiently again.',
  }
];
